import React from 'react'
import TypingEffect from './TypingEffect'
import CodeBlock from '../CodeBlock'
import LiveCode from "./LiveCode"

const ChatPost = () => {
  let testCode = "console.log('HEY GUY!');";
  let testText = "HERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDS"
  let displayText = "Welcome, This is my Blog! hopefully I can put some useful stuff in here. Blogs will be rendered below in order from newest to oldest. You can also navigate through recent blogs using the sidebar. Later on, the sidebar may become collapsible."
  return (
    <div id="ChatPost" className='w-full'>
      <ol>
        <li className='loading-list-li'>
        <TypingEffect text={displayText} typingSpeed={20} />

        </li>
        <li className='loading-list-li'>
        <LiveCode code={testCode} typingSpeed={20} />
          
          </li>
      </ol>

            
    </div>
  )
}

export default ChatPost