import React from 'react'
import TypingEffect from './TypingEffect'
import CodeBlock from '../CodeBlock'
import LiveCode from "./LiveCode"
import LoadingList from './LoadingList'

const ChatPost = () => {
  let testCode = "console.log('HEY GUY!');";
  let testText = "HERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDSHERE IS A REALLY LONG EAXAMPLE OF TEXT AND WORDS ASDASDS"
  let displayText = "Welcome, This is my Blog! hopefully I can put some useful stuff in here. Blogs will be rendered below in order from newest to oldest. You can also navigate through recent blogs using the sidebar. Later on, the sidebar may become collapsible."
  let introTyper = <TypingEffect text={displayText} typingSpeed={15}/>
  let introCode = <LiveCode code={"console.log('Hello World!')"} typingSpeed={15} />
  return (
    <div id="ChatPost" className='w-full'>
        <LoadingList items={[introTyper, introCode]} waitTimer={3200} />
    </div>
  )
}

export default ChatPost